name: Documentation Request
description: Request a change to the docs.
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: section
    attributes:
      label: What part of the docs?
      placeholder: ex. "Installation instructions."
    validations:
      required: true
  - type: textarea
    id: change
    attributes:
      label: What should we add or fix?
      placeholder: ex. "Add detailed steps for installing dependencies."
